# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/myconfessions',
                'doc_host': 'https://blaxpyda.github.io',
                'git_url': 'https://github.com/blaxpyda/myconfessions',
                'lib_path': 'myconfessions'},
  'syms': {'myconfessions.core': {'myconfessions.core.foo': ('core.html#foo', 'myconfessions/core.py')}}}
